project_id = "gggziewyeqsnuixwhvoe"

[functions.stripe-webhook]
verify_jwt = false

[functions.book-lesson]
verify_jwt = true

[functions.cal-webhook]
verify_jwt = false

[functions.chat]
verify_jwt = true
