-- ============================================================
-- TutorEnglishPro - visitor_views schema + title column
-- ------------------------------------------------------------
-- Run in Supabase SQL Editor (Dashboard > SQL Editor > New query).
--
-- 1) Creates the visitor_views table if it does not exist.
-- 2) Adds the `title` column used by "Top Pages" so the admin
--    console shows real page names (tracked from document.title).
-- ============================================================

create table if not exists public.visitor_views (
  id bigint generated by default as identity primary key,
  path text not null,
  referrer text,
  title text,
  device text,
  browser text,
  os text,
  country text,
  screen text,
  created_at timestamptz not null default now()
);

-- Columns required by js/ads.js track() (analytics built into the Ads & SEO panel).
-- Safe to run even if they already exist.
alter table public.visitor_views add column if not exists title text;
alter table public.visitor_views add column if not exists device text;
alter table public.visitor_views add column if not exists browser text;
alter table public.visitor_views add column if not exists os text;
alter table public.visitor_views add column if not exists country text;
alter table public.visitor_views add column if not exists screen text;

-- Lightweight read policy so the logged-in admin can view stats.
alter table public.visitor_views enable row level security;

drop policy if exists "admin can read visitor views" on public.visitor_views;
create policy "admin can read visitor views"
  on public.visitor_views for select
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

-- Inserts come from the anon key (js/ads.js best-effort tracking).
drop policy if exists "anyone can insert visitor views" on public.visitor_views;
create policy "anyone can insert visitor views"
  on public.visitor_views for insert
  with check (true);